# Generated by Django 6.0.5 on 2026-05-07 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='candidates/photos/')),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates_candidate',
            },
        ),
        migrations.CreateModel(
            name='CandidateMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='candidates/members/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='candidates.candidate')),
            ],
            options={
                'db_table': 'candidates_member',
            },
        ),
    ]
