# Generated by Django 6.0.5 on 2026-05-07 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('vote', 'Vote'), ('candidate_register', 'Candidate Register'), ('candidate_approve', 'Candidate Approve'), ('candidate_reject', 'Candidate Reject'), ('voter_create', 'Voter Create'), ('voter_update', 'Voter Update'), ('voter_delete', 'Voter Delete')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
