# Generated by Django 6.0.5 on 2026-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pemilih', 'Pemilih'), ('paslon', 'Paslon'), ('pengawas', 'Pengawas Pemilu')], default='pemilih', max_length=10),
        ),
    ]
